<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="Mutation.Tests" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Azure.AI.Vision.ImageAnalysis" />
		<PackageReference Include="Concentus" />
		<PackageReference Include="Concentus.Oggfile" />
		<PackageReference Include="Deepgram" />
		<PackageReference Include="OpenAI" />
		<PackageReference Include="Polly" />
		<PackageReference Include="NAudio" />
		<PackageReference Include="SoundTouch.Net" />
		<PackageReference Include="System.Speech" />
	</ItemGroup>
</Project>
